### ISSUE TITLE
Ensure correct procedure while generatin gl0buli

### ISSUE THREAD

**Issue by s1lvester** [Cheatha/gl0buli#11]
After demonstration during an enlightening session with guru „Cheatha“ I have to insist on proper procedure when generating gl0buli.

See: https://youtu.be/9xWQxdPLpLU

**Comment by Cheatha** [comment]
Thanks! Your video helped a lot to understand the scie… "magic" behind this stuff!  

Fixed in 51d1172084aae6ca07f32a32845d849da98e1d2d
