### ISSUE TITLE
Implement Selectable dilution levels

### ISSUE THREAD

**Issue by tabascoeye** [Cheatha/gl0buli#2]
There is no comment on which ~~delusion~~ dilution level is chosen.
This is highly important for a working code therapy.

I would recommend the most commonly used C30.
This will make the script slow, but it will surely yield a much greater effect for the final gl0buli!

C30 is a 1:10^60 dilution. [In steps of: 1) dilute 1:100 2) shake 10 times]

**Comment by Cheatha** [comment]
:+1:

**Comment by Cheatha** [comment]
Thanks! This issue has been resolved in https://github.com/Cheatha/gl0buli/commit/51d1172084aae6ca07f32a32845d849da98e1d2d
